### ISSUE TITLE
회원 권한 사용자 기능개발

### ISSUE THREAD

**Issue by lucinda96** [ssg-240304-java2/JD-JustDo#5]
- [x] 회원계정 로그인
- [x] 회원가입 
- [x] 로그인한 회원 정보 출력
- [x] 센터이용권 구매
- [x] 회원계정 로그아웃

**Comment by ptecc208** [comment]
구현 완료하였으나 세부 예외 처리 및 가독성을 올리기 위한 코드 리팩토링 예정입니다

**Comment by ptecc208** [comment]
0426 공통 기능 구현 및 강사 배정, 예외처리 추가
